name: functions-actions

on:
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: marco-polo
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'deploy'  # Directory to deploy, containing binary and host.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@v2
      - name: Install with RustUp
        shell: bash
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install musl
        run: sudo apt-get install -y --no-install-recommends musl-tools
      - name: Add Target
        shell: bash
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build release
        shell: bash
        run: |
          cargo build --release --target=x86_64-unknown-linux-musl
          # Create deploy directory and copy necessary files
          mkdir -p deploy
          cp target/x86_64-unknown-linux-musl/release/handler deploy/  # Matches Cargo.toml name
          cp host.json deploy/
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Azure Functions action
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          respect-funcignore: true